language: node_js
sudo: required
services:
    - docker
node_js:
    - 13.6.0
before_install:
    - echo "some stuff here"
install:
    - echo "some stuff here"
script:
    - echo "skipping tests for now"
after_success:
    - echo "some stuff here"
deploy:
    - provider: script
      script: './deploy.sh'
      skip_cleanup: true
      on:
          branch: master
