language: node_js
sudo: required
services:
    - docker
node_js:
    - 13.6.0
env:
    - WORK_DIR=/home/autumn-bot/release/autumn-bot-ts
addons:
    apt:
        packages:
            - sshpass
before_install:
    - chmod a+x ./.travis/deploy.sh
    - openssl aes-256-cbc -K $encrypted_2c66c6413907_key -iv $encrypted_2c66c6413907_iv -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/deploy_rsa
    - ssh-add .travis/deploy_rsa
install:
    - ssh-keyscan $SERVER_NAME >> $HOME/.ssh/known_hosts
    - cd $TRAVIS_BUILD_DIR $$ npm install
script:
    - echo "skipping tests for now"
after_success:
    - cd $TRAVIS_BUILD_DIR && docker build -t autumnbot:dev-"$TRAVIS_BUILD_NUMBER" . --label "version=$TRAVIS_BUILD_NUMBER" --label "commitMessage=$TRAVIS_COMMIT_MESSAGE" --label "commit=$TRAVIS_COMMIT"
deploy:
    - provider: script
      script: './.travis/deploy.sh'
      skip_cleanup: true
      on:
          branch: master
